### ISSUE TITLE
如果在子RecycleView下父recycleview还有其他的item，这时候子recycleview就不能吸顶了，要吸顶是不是只能是子recycleview是最后一个item啊

### ISSUE THREAD

**Issue by TowerYe** [JasonGaoH/NestedRecyclerView#12]

**Comment by JasonGaoH** [comment]
是的

**Comment by JasonGaoH** [comment]
你这个item为啥要放父RecyclerView里面，有啥特殊的原因吗

**Comment by TowerYe** [comment]
> 你这个item为啥要放父RecyclerView里面，有啥特殊的原因吗

就相当于是京东，淘宝的商品列表，其中有个item的样式是具有tablayout的，当recycleview中有这个样式的item时，就需要将tablayout吸顶，但是这个item的位置是不确定的，不一定是在最后一个，有可能在中间，所以它之后还会有其他样式的item

**Comment by JasonGaoH** [comment]
> > 你这个item为啥要放父RecyclerView里面，有啥特殊的原因吗
> 
> 就相当于是京东，淘宝的商品列表，其中有个item的样式是具有tablayout的，当recycleview中有这个样式的item时，就需要将tablayout吸顶，但是这个item的位置是不确定的，不一定是在最后一个，有可能在中间，所以它之后还会有其他样式的item

有视频看看嘛，我没太明白啥意思😬

**Comment by TowerYe** [comment]
> > > 你这个item为啥要放父RecyclerView里面，有啥特殊的原因吗
> > 
> > 
> > 就相当于是京东，淘宝的商品列表，其中有个item的样式是具有tablayout的，当recycleview中有这个样式的item时，就需要将tablayout吸顶，但是这个item的位置是不确定的，不一定是在最后一个，有可能在中间，所以它之后还会有其他样式的item
> 
> 有视频看看嘛，我没太明白啥意思😬

就是相当于有个业务需求，好比你的demo里面，整个列表一共有10条数据，前面5条数据是你的parent item卡片，第6条是具有tab+viewpager的数据，所以第6条数据为了实现tab吸顶需要用子recycleview，然后7-10条又是parent item卡片，简单来说就是tab不在最后一个，在列表的任一位置，都可以实现吸顶的效果。
在MainActivity中加入如下代码，然后关闭子recycleview的上拉加载更多，

![1587707590842](https://user-images.githubusercontent.com/18652326/80179420-18750e00-8633-11ea-8085-5aa36bdc88c9.jpg)
![1587707563682](https://user-images.githubusercontent.com/18652326/80179421-1a3ed180-8633-11ea-9c36-e05f9e61d550.jpg)

**Comment by JasonGaoH** [comment]
> > > > 你这个item为啥要放父RecyclerView里面，有啥特殊的原因吗
> > > 
> > > 
> > > 就相当于是京东，淘宝的商品列表，其中有个item的样式是具有tablayout的，当recycleview中有这个样式的item时，就需要将tablayout吸顶，但是这个item的位置是不确定的，不一定是在最后一个，有可能在中间，所以它之后还会有其他样式的item
> > 
> > 
> > 有视频看看嘛，我没太明白啥意思😬
> 
> 就是相当于有个业务需求，好比你的demo里面，整个列表一共有10条数据，前面5条数据是你的parent item卡片，第6条是具有tab+viewpager的数据，所以第6条数据为了实现tab吸顶需要用子recycleview，然后7-10条又是parent item卡片，简单来说就是tab不在最后一个，在列表的任一位置，都可以实现吸顶的效果。
> 在MainActivity中加入如下代码，然后关闭子recycleview的上拉加载更多，
> 
> ![1587707590842](https://user-images.githubusercontent.com/18652326/80179420-18750e00-8633-11ea-8085-5aa36bdc88c9.jpg)
> ![1587707563682](https://user-images.githubusercontent.com/18652326/80179421-1a3ed180-8633-11ea-9c36-e05f9e61d550.jpg)

嗯嗯，我明白你的意思，这种看起来目前是不支持的，不是很好处理
