### ISSUE TITLE
能支持一下SmartRefreshLayout吗

### ISSUE THREAD

**Issue by moyulong** [JasonGaoH/NestedRecyclerView#13]
用SmartRefreshLayout有冲突

**Comment by JasonGaoH** [comment]
好的，后面加一下。

**Comment by thisleo** [comment]
smartRefreshLayout.setScrollBoundaryDecider(new ScrollBoundaryDecider() {
            @Override
            public boolean canRefresh(View content) {
                if (recyclerView.isScrollTop()) {
                    return true;
                }
                return false;
            }

            @Override
            public boolean canLoadMore(View content) {
                return false;
            }
        });
可以通过这个方式解决SmartRefreshLayout的下拉刷新冲突
