### ISSUE TITLE
tab从吸顶到非吸顶时，建议将所有tab页面的滑动位置重置。

### ISSUE THREAD

**Issue by jarvan11** [JasonGaoH/NestedRecyclerView#14]
问题重现步骤： A tab 所在页面向上滑动到吸顶后一定位置（假如是4 position 位置），切换到B tab ，然后在B tab 所在页面再向下滑动到非吸顶，再切换到A tab，此时A tab所在页面由于没有重置滑动位置，还是停留在position为4的位置，此时无论向上还是向下滑动都无法看到position为4之前的内容，需要继续滑动到吸顶一定距离再向下滑动才能正常。

**Comment by JasonGaoH** [comment]
好的，我近期会处理下，感谢反馈。

**Comment by JasonGaoH** [comment]
已修复。

**Comment by jarvan11** [comment]
> 已修复。

这样处理修复了下滑可以看到position为4之前的内容，但是在此页面上滑有问题，一直上滑都是子recyclerVIew滑动，TAB无法吸顶了。看了京东和淘宝的app的效果，tab从吸顶到非吸顶时，都会将所有tab页面的滑动位置重置为position为0位置。

**Comment by JasonGaoH** [comment]
这样啊，明白了

**Comment by csgsky** [comment]
> 这样啊，明白了

可以支持么
