### ISSUE TITLE
滑动的时候出现页面抖动

### ISSUE THREAD

**Issue by PokerMman** [JasonGaoH/NestedRecyclerView#15]
1：ParentRecyclerView适配器里面有多个ViewItemType， 每个页面item的高度是不一样的
2：childRecyclerView 的tab置顶之后，缓慢向下滑动，滑动tab 处于页面中间的时候会出现抖动，突然向下滑动了一段距离，导致了页面的闪烁

**Comment by JasonGaoH** [comment]
能给个Demo或者录个屏不？

**Comment by PokerMman** [comment]
链接: https://pan.baidu.com/s/1AM3Q0mS3pfhGpxee9YFcrw 提取码: jep3

已上传录屏

**Comment by PokerMman** [comment]
查出来问题了。是因为图片动态高度的问题，需要全部设置固定高度
