### ISSUE TITLE
ChildRecyclerView置顶滑动卡顿

### ISSUE THREAD

**Issue by PokerMman** [JasonGaoH/NestedRecyclerView#16]
Tab置顶之后
切换到其他tab
一下子向上滑动 childRecyclerView 
可以发现childRecyclerView 会突然一下子卡主不滑动了
当childRecyclerView 每次加载好数据之后 就不会出现这样的问题

**Comment by PokerMman** [comment]
Demo样式就可以看见

**Comment by PokerMman** [comment]
kotlin 版本有问题  java 好像ok的

**Comment by 17554265585** [comment]
都有这个问题

**Comment by galaxylei** [comment]
同问，有人解决这个问题吗？

**Comment by JasonGaoH** [comment]
我看一下这个问题。

**Comment by JasonGaoH** [comment]
我这边看起来Java版本没有这个问题

**Comment by galaxylei** [comment]
我这里是这样解决的，不知道对不对：
 @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (ev != null && ev.getAction() == MotionEvent.ACTION_DOWN) {
            //ACTION_DOWN的时候重置加速度
            velocityY = 0;
            stopScroll();
        }
        if (!(ev == null || ev.getAction() == MotionEvent.ACTION_DOWN)) {
            //在ACTION_MOVE的情况下，将lastY置为0
            if (!isScrollEnd() ) {   //之前没有这个判断
                lastY = 0f;
            }
            canScrollVertically.set(!isScrollEnd());
        }
        try {
            return super.dispatchTouchEvent(ev);
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

**Comment by JasonGaoH** [comment]
> 我这里是这样解决的，不知道对不对：
> @override
> public boolean dispatchTouchEvent(MotionEvent ev) {
> if (ev != null && ev.getAction() == MotionEvent.ACTION_DOWN) {
> //ACTION_DOWN的时候重置加速度
> velocityY = 0;
> stopScroll();
> }
> if (!(ev == null || ev.getAction() == MotionEvent.ACTION_DOWN)) {
> //在ACTION_MOVE的情况下，将lastY置为0
> if (!isScrollEnd() ) { //之前没有这个判断
> lastY = 0f;
> }
> canScrollVertically.set(!isScrollEnd());
> }
> try {
> return super.dispatchTouchEvent(ev);
> } catch (Exception e) {
> e.printStackTrace();
> return false;
> }
> }

好像不行，Kotlin版本是有问题。

**Comment by galaxylei** [comment]
为啥我们刚好相反，我们是java版本有问题....kotlin没有问题

**Comment by JasonGaoH** [comment]
这么奇怪，我改了一下，你们可以看看有没有解决，具体原因还在看。

**Comment by JasonGaoH** [comment]
> 为啥我们刚好相反，我们是java版本有问题....kotlin没有问题

你用的啥手机？

**Comment by galaxylei** [comment]
华为 nova 7

**Comment by JasonGaoH** [comment]
你看看现在有没有问题，我这边看OK了。
