### ISSUE TITLE
可以支持多次吸顶吗？

### ISSUE THREAD

**Issue by galaxylei** [JasonGaoH/NestedRecyclerView#18]
可以支持多次吸顶吗？

**Comment by JasonGaoH** [comment]
是指多个吸顶嘛？

**Comment by galaxylei** [comment]
> 是指多个吸顶嘛？

不知道我们说的是不是一回事，就是有多个子recyclerview

**Comment by JasonGaoH** [comment]
> > 是指多个吸顶嘛？
> 
> 不知道我们说的是不是一回事，就是有多个子recyclerview

这种看起来不好支持。
