### ISSUE TITLE
设置ParentRecyclerView的layoutManager为StaggeredGridLayoutManager会有问题

### ISSUE THREAD

**Issue by galaxylei** [JasonGaoH/NestedRecyclerView#19]
1、在调用Parent.initLayoutManager()方法前，为ParentRecyclerView再设置一个StaggeredGridLayoutManager，会导致滑动冲突，这是为啥？
2、如果给ParentRecyclerView设置了StaggeredGridLayoutManager，initLayoutManager方法里面的LinearLayoutManager也必须设置为StaggeredGridLayoutManager，这个问题也不清楚是为啥？

**Comment by JasonGaoH** [comment]
> 1、在调用Parent.initLayoutManager()方法前，为ParentRecyclerView再设置一个StaggeredGridLayoutManager，会导致滑动冲突，这是为啥？
> 2、如果给ParentRecyclerView设置了StaggeredGridLayoutManager，initLayoutManager方法里面的LinearLayoutManager也必须设置为StaggeredGridLayoutManager，这个问题也不清楚是为啥？

为什么要重复设置这个LayoutManager呢？

**Comment by galaxylei** [comment]
源码中的initLayoutmanager是初始化一个linearlayoutmanager，这个肯定是不够用的，得用StaggeredGridLayoutManager

**Comment by JasonGaoH** [comment]
> 源码中的initLayoutmanager是初始化一个linearlayoutmanager，这个肯定是不够用的，得用StaggeredGridLayoutManager

那你可以把initLayoutManger中改成StaggeredGridLayoutManager，这样应该满足需求吧

**Comment by galaxylei** [comment]
可以的，我自测也没有问题，只不过很奇怪，为啥不能设置两个layoutmanager了。
