### ISSUE TITLE
滑动问题

### ISSUE THREAD

**Issue by TokenYc** [JasonGaoH/NestedRecyclerView#4]
当ChildRecyclerView下滑时，ChildRecyclerView滑动到顶部（非fling），此时ParentRecyclerView不会继续下滑。
可以查看下面这个链接里的视频帮助理解：
https://youzai-1258403966.cos.ap-shanghai.myqcloud.com/70611dc361b5f93d817f50731018918d.mp4

**Comment by JasonGaoH** [comment]
好的，我再确认下，你这个视频里是你下滑的时候，手指没放开，会出现tab上面的部分滑不下来是吧？

**Comment by JasonGaoH** [comment]
修复的代码进了，你可以再看下效果。

**Comment by TokenYc** [comment]
嗯，正常使用没问题。配合SwipeRefreshLayout使用存在一些问题，我自己兼容了。
多谢~

**Comment by JasonGaoH** [comment]
额，请问，配合 SwipeRefreshLayout 使用的问题具体是什么问题，能否告知一下，我自己这边没和 SwipeRefreshLayout 一起用过。

**Comment by TokenYc** [comment]
滑动冲突。在demo的最底层布局加一个SwipeRefreshLayout就可以复现了。
